"""add guest mode fields

Revision ID: 35aca9b520a4
Revises: eef30741d4a3
Create Date: 2026-03-20 10:41:00.796591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35aca9b520a4'
down_revision: Union[str, None] = 'eef30741d4a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('chat_sessions', sa.Column('share_token', sa.String(), nullable=True))
    op.add_column('chat_sessions', sa.Column('guest_can_chat', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_chat_sessions_is_public'), 'chat_sessions', ['is_public'], unique=False)
    op.create_index(op.f('ix_chat_sessions_share_token'), 'chat_sessions', ['share_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_sessions_share_token'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_is_public'), table_name='chat_sessions')
    op.drop_column('chat_sessions', 'guest_can_chat')
    op.drop_column('chat_sessions', 'share_token')
    op.drop_column('chat_sessions', 'is_public')
    # ### end Alembic commands ###
