"""fix_resume_owner_relationship

Revision ID: 64c865ed31f2
Revises: 1fa9cbc20bf7
Create Date: 2026-03-19 12:04:11.794230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64c865ed31f2'
down_revision: Union[str, None] = '1fa9cbc20bf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
