"""make_resume_id_nullable_in_chat_messages

Revision ID: 82913b67bcc6
Revises: f161e7f0a3eb
Create Date: 2026-03-24 03:46:13.662798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82913b67bcc6'
down_revision: Union[str, None] = 'f161e7f0a3eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'resume_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'resume_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
