"""fix_relationships_and_uuids

Revision ID: dfe5c900fca3
Revises: 4547f99bfb72
Create Date: 2026-03-19 12:13:25.547356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfe5c900fca3'
down_revision: Union[str, None] = '4547f99bfb72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
