"""add_cascade_to_document_chunks

Revision ID: f161e7f0a3eb
Revises: 35aca9b520a4
Create Date: 2026-03-20 23:47:58.256420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f161e7f0a3eb'
down_revision: Union[str, None] = '35aca9b520a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('document_chunks_resume_id_fkey'), 'document_chunks', type_='foreignkey')
    op.create_foreign_key(None, 'document_chunks', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.create_foreign_key(op.f('document_chunks_resume_id_fkey'), 'document_chunks', 'resumes', ['resume_id'], ['id'])
    # ### end Alembic commands ###
